services:
  app:
    build:
      context: .
    container_name: truehabits-app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./logs:/logs
      - ./data:/data
      - ./credentials.json:/app/credentials.json
    env_file:
      - .env
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: postgres:14
    container_name: truehabits-db
    ports:
      - "5440:5432"
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
